### ISSUE TITLE
Visual Bug: Thumbnails Don't Scale To Take All Width

### ISSUE THREAD

**Issue by Mercencium** [thejaviertc/steam-workshop-stats#1338]
## Both in Chromium and Firefox:
![image](https://github.com/user-attachments/assets/626859e5-4603-471e-91f2-69a40edc48e3)

## Fixed by adding `width: 100%` CSS to the `<img>` tag.
![image](https://github.com/user-attachments/assets/ce0ee13b-fa56-4f8e-80bf-70db9326ec1d)

**Comment by thejaviertc** [comment]
Fixed in [bf39a70](https://github.com/thejaviertc/steam-workshop-stats/commit/bf39a703cb49f3766185289dd36a861aa1178c13), thanks for reporting it.
