### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by anormalbox** [thejaviertc/steam-workshop-stats#263]
TypeError: Failed to fetch
Access to fetch at 'https://javiertcs-api.herokuapp.com/steam-workshop-stats?url=http://steamcommunity.com/id/javiertc/' from origin 'https://thejaviertc.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by thejaviertc** [comment]
The API was down. I restarted it and it's working now
