### ISSUE TITLE
Possible to show Likes and Dislikes?

### ISSUE THREAD

**Issue by mcrksman** [thejaviertc/steam-workshop-stats#34]
Hey nice work, Is it possible to get detailed stats from steam like the Likes and Dislikes on workshop items?

**Comment by thejaviertc** [comment]
> Hey nice work, Is it possible to get detailed stats from steam like the Likes and Dislikes on workshop items?

Thanks you.
I'm sorry but I think is impossible, because the Steam API doesn't give you the likes/dislikes from and addon.
The only way it could be done is to web scrapping the steam website, but that would be too slow and expensive.

Regards

**Comment by thejaviertc** [comment]
I was watching old issues and I have just saw this. I don't know when I realized how to do it and was implemented 1 year ago or something like that.
