### ISSUE TITLE
QoL feature about Steam Profile URL input

### ISSUE THREAD

**Issue by rslgp** [thejaviertc/steam-workshop-stats#601]
is that possible to add a feature that ignores the path after user id/profile?
only if url occurences "/" >= 5  (to prevent incompatibilities with future steam changes
checks if url have id or profile, and extract the next string path from url

https://steamcommunity.com/id/USER/myworkshopfiles/?appid=###
https://steamcommunity.com/profile/USER/myworkshopfiles/?appid=###

is it possible to ignores the extra data content, just extract the https://steamcommunity.com/%s/%s

it will be a nice feature to simply copy and paste the steam workshop url, and my browser (client side) trims that to the correct one

i try to send a PR with that change, but i dont have familiarity with svelte

**Comment by thejaviertc** [comment]
Yes, I know this problem.

I'm working on a new major version with a lot of new features, but it's going to take a while.

I'll try to add a temporal patch soon.

Thanks you.

**Comment by thejaviertc** [comment]
Fixed in [thejaviertc/javiertcs-api](https://github.com/thejaviertc/javiertcs-api/commit/03c4e48bd6f32f0532f587e0749992e935f62d55) last commit
