### ISSUE TITLE
QoL request: input using url Query Parameters

### ISSUE THREAD

**Issue by rslgp** [thejaviertc/steam-workshop-stats#632]
hi javier, its is amazing the new release, well done! 
i really enjoy the new summary on top, including total like deslike, and the stars rating
is possible to add a way to do the request via url like

https://thejaviertc.github.io/steam-workshop-stats/fetch-user?q=ALL_WORKING_INPUTS

**Comment by thejaviertc** [comment]
Yes, it can be done.

It can be useful so that the profile you have searched for remains in the browser history, save it as favorites and not have to always put it...

**Comment by thejaviertc** [comment]
I had everything prepared for deploy 2.0.0 with this, but dynamic routes with SvelteKit and Github Pages seems to not work or I need to do something that I don't know. Tomorrow I'll try to ask someone for help

**Comment by thejaviertc** [comment]
Finally fixed and deployed with 2.0.0
