### ISSUE TITLE
Thoughts on the Graphs display

### ISSUE THREAD

**Issue by librarianmage** [thejaviertc/steam-workshop-stats#788]
Thanks for this project!

Since the current graphs aren't related to time, a line chart feels like a poor representation of the data. Perhaps a bar chart would represent it better?

The ability to rearrange the addons would be useful as well :)

**Comment by thejaviertc** [comment]
Sorry for replying too late @librarianmage.

- In the next hour/hours, the graphs will be changed to a bar chart (#807).
- In the future I'll add an option to sort addons (#808).

Thanks for the comment
